# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c244ad6b264ecdea95bb70f4c06cead126f43a85ca3870ecabf0b8fb62df128abede759f7b7a04ff9562e52c8e82283e1e27684adc9951c6bbc3d3665b5d9a56

test:
  secret_key_base: a6bbc9882a7083e1e95cb08ad0914261fee12430fff4d777fcff51d0756a14ec3cdb90b212c8004a75b0763edcb0d61b2e8ae2b40475a87bfcbbecef392570b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
